name: build-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter_server=2.7.1 # https://anaconda.org/conda-forge/jupyter_server/files
  - jupyterlite-core=0.1.2 # https://anaconda.org/conda-forge/jupyterlite-core/files
  - jupyterlite-xeus-python=0.9.4 # https://anaconda.org/conda-forge/jupyterlite-xeus-python/files