title: "Add your title here..."
labels: ["limitation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to test Brightway Live and report a limitation. \
        Please fill out the following form to help us improve this tool.
  - type: dropdown
    attributes:
      label: Affected Brightway Package
      options:
        - bw2data
        - bw2calc
        - bw2io
        - bw2analyzer
        - other
      multiple: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's broken or not working as expected?
      description: Please describe the limitation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's the error message?
      description: Please paste the complete error message here.
      render: true
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Compare also [the open issues](https://github.com/brightway-lca/brightway-live/issues) for this project.
  - type: checkboxes
    attributes:
      label: I have done the following:
    options:
      - label: I searched for similar discussions and issues and didn't find any.
        required: true