title: ""
labels: ["limitation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to test Brightway Live and report a limitation. \
        Please fill out the following form to help us improve this tool.
  - type: dropdown
    attributes:
      label: Affected Brightway Package
      options:
        - `bw2data`
        - `bw2calc`
        - `bw2io`
        - `bw2analyzer`
        - other
      multiple: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's broken or not working as expected?
      description: Please describe the limitation and paste the relevant Python input/output.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Compare also [the open issues](https://github.com/brightway-lca/brightway-live/issues) for this project.