name: bw_live_pyodide
channels:
  - conda-forge
  - conda-forge/label/bw2io_dev
  - conda-forge/label/bw2data_dev
  - conda-forge/label/bw2calc_dev
  - nodefaults
dependencies:
  - python=3.10
  - jupyterlab
  - scipy
  - pandas
  # BRIGHTWAY CORE
  - bw2io=0.9.dev22 # https://anaconda.org/conda-forge/bw2io/files # loaded from conda-forge under the `dev` label
  - bw2data=4.0.dev27 # https://anaconda.org/conda-forge/bw2data/files # loaded from conda-forge under the `dev` label
  - bw2calc=2.0.dev14 # https://anaconda.org/conda-forge/bw2calc/files  # loaded from conda-forge under the `dev` label