name: sphinx_brightway_live
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.11
  - ipython
  # sphinx
  - sphinx=7.3.7 # core builder # https://anaconda.org/conda-forge/sphinx/files
  # theme and extensions
  - pydata-sphinx-theme=0.15.2 # website theme # https://anaconda.org/conda-forge/pydata-sphinx-theme/files
  - myst-parser=3.0.1 # Markdown support # https://anaconda.org/conda-forge/myst-parser/files
  - sphinx-design=0.5.0 # responsive web component support # https://anaconda.org/conda-forge/sphinx-design/files
  - sphinx-notfound-page=1.0.0 # custom 404 page # https://anaconda.org/conda-forge/sphinx-notfound-page/files
  - sphinx-favicon=1.0.1 # for custom favicons # https://anaconda.org/conda-forge/sphinx-favicon/files
  - sphinx-copybutton=0.5.2 # for copy button in code blocks # https://anaconda.org/conda-forge/sphinx-copybutton/files
  - linkify-it-py=2.0.3 # for beautified github links # https://anaconda.org/conda-forge/linkify-it-py/files
  # build process
  - sphinx-autobuild=2024.4.16 # live-html support # https://anaconda.org/conda-forge/sphinx-autobuild/files
  # web assembly
  - jupyterlite-sphinx=0.15.0 # jupyterlite support # https://anaconda.org/conda-forge/jupyterlite-sphinx/files
  - jupyterlite-pyodide-kernel=0.3.1 # pyodide support # https://anaconda.org/conda-forge/jupyterlite-pyodide-kernel/files